version: '3.7'
services:
  db:
    image: postgres:11.8
    environment:
       - POSTGRES_DB=Shop
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    ports:
       - 5234:15234
    volumes:
       - ./db-data/postgres:/var/lib/postgresql/data
    restart: always

  auth:
    build:
      context: .
      dockerfile: ./Auth/Dockerfile
    environment:
      - DEBUG=0
    depends_on:
      - db
    command: flask run -h 0.0.0.0 -p 1240 # Default
    ports:
      - 1240:1240
    restart: always

  web:
    build:
      context: .
      dockerfile: ./Shop/Dockerfile
    environment:
      - DEBUG=0
    depends_on:
      - db
      - auth
    command: flask run -h 0.0.0.0 -p 1237 
    ports:
      - 1237:1237
    restart: always
