FROM python:3.8.2

WORKDIR /home/prod/shop
COPY ./Auth .

RUN pip3 install -r py-requirements.txt


#RUN apt-get update && apt-get upgrade

#ENTRYPOINT ["python3", "-m", "flask", "run"]



#LABEL maintainer="me@aphanasiy.ru"



#CMD python3 hello.py > kek.txt



